# Docker
# Build a Docker image 
# https://docs.microsoft.com/azure/devops/pipelines/languages/docker

trigger:
    - master
    
    resources:
    - repo: self
    
    variables:
      tag: |
        $(Build.BuildNumber)
        latest
    
    
    stages:
    - stage: Build
      displayName: Build image
      jobs:  
      - job: Build
        displayName: Build
        pool:
          vmImage: 'ubuntu-latest'
        steps:
        - task: Docker@2
          inputs:
            containerRegistry: 'fra-01 Docker Registry'
            repository: 'jwt-sample-app'
            command: 'build'
            Dockerfile: '**/Dockerfile'
            tags: |
              $(Build.BuildNumber)
              latest
        - task: Docker@2
          inputs:
            containerRegistry: 'fra-01 Docker Registry'
            repository: 'jwt-sample-app'
            command: 'push'
            tags: |
              $(Build.BuildNumber)
              latest
        - task: PublishBuildArtifacts@1
          inputs:
            pathToPublish: $(Build.ArtifactStagingDirectory)
            artifactName: jwt-sample-app-$(Build.BuildNumber)