tags:
- name: tokens
  description: tokens API

paths:
# [POST] generate-jwt
  /api/v1/tokens/generate-jwt/:
    post:
      tags:
      - tokens
      summary: Generate JWT Token
      parameters:
      - name: body
        in: body
        description: CreateJwtTokenModel
        required: true
        schema:
          $ref: '#/definitions/create-jwt-token-model'
      responses:
        201:
          description: 'Created'
        400:
          description: 'Bad Request'
        500:
          description: 'Server Error'

# [POST] validate-jwt
/api/v1/tokens/validate-jwt/:
  post:
    tags:
    - tokens
    summary: Validate JWT Token
    parameters:
    - name: body
      in: body
      description: ValidateJwtTokenModel
      required: true
      schema:
        $ref: '#/definitions/validate-jwt-token-model'
    responses:
      202:
        description: 'Accepted'
      400:
        description: 'Bad Request'
      500:
        description: 'Server Error'

# definitions
definitions:
  create-jwt-token-model:
    type: object
    required:
      - givenName
      - familyName
      - preferredUsername
      - email
      - sub
      - iss
      - exp
      - secret
    properties:
      givenName:
        type: string
        description: User Given Name(First Name)
      familyName:
        type: string
        description: User Fammiy Name(Last Name)
      preferredUsername:
        type: string
        description: User Preferred UserName
      email:
        type: string
        format: email
        description: User email
      sub:
        type: string
        description: JWT Subject
      iss:
        type: string
        format: uri
        description: JWT Issuer
      exp:
        type: string
        format: date
        description: JWT Expiration date
      secret:
        type: string
        description: JWT Hash string

  validate-jwt-token-model:
    type: object
    required:
        - token
        - secret
    properties:
      token:
        type: string
        description: JWT Token
      secret:
        type: string
        description: JWT Verification Token Secret

schemes:
 - https
 - http
